[package]
name = "buchklub_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
handlebars = { version = "6.0.0", features = [] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.122", features = ["preserve_order"] }
